defmodule Muro.Emit do
  @moduledoc """
  Emit run definitions to Elixir. Specs and evidence erase.
  A spec never becomes evidence. Evidence never becomes a run.

  A checked run Stream is emitted as `Stream.unfold/2`. The pair in an
  unfold body is `{head, next_seed}`. `uncons` is two replayable views
  (`Enum.take/2` + `Stream.drop/2`); affinity was already checked.
  """

  alias Muro.Ast

  def emit_module(module, book) when is_atom(module) do
    runs = Enum.filter(book, &(&1.mode == :run))
    funs = runs |> Enum.map(&emit_def(&1, book)) |> Enum.join("\n\n")

    except =
      if Enum.any?(runs, &(&1.name == "length")) do
        "  import Kernel, except: [length: 1]\n"
      else
        ""
      end

    """
    defmodule #{inspect(module)} do
      # Generated by Muro. Evidence never becomes a run.
    #{except}
    #{indent(funs, 2)}
    end
    """
  end

  defp emit_def(%{name: name, type: ty, body: body} = d, book) do
    {:ok, ty_db} = Ast.to_db(ty)
    {:ok, body_db} = Ast.to_db(body)
    {erased, arity} = telescope(ty_db, 0, [])
    inner = peel_lams(body_db, arity)

    args =
      0..(arity - 1)//1
      |> Enum.reject(&(&1 in erased))
      |> Enum.map(&"x#{&1}")

    expr = emit_db(inner, arity, book)
    kw = if Map.get(d, :export, true), do: "def", else: "defp"

    if args == [] do
      "#{kw} #{safe(name)} do\n  #{expr}\nend"
    else
      "#{kw} #{safe(name)}(#{Enum.join(args, ", ")}) do\n  #{expr}\nend"
    end
  end

  defp telescope({:pi, :erased, _, b}, i, er), do: telescope(b, i + 1, [i | er])
  defp telescope({:pi, _, _, b}, i, er), do: telescope(b, i + 1, er)
  defp telescope(_, i, er), do: {er, i}

  defp peel_lams({:lam, _, _, t}, n) when n > 0, do: peel_lams(t, n - 1)
  defp peel_lams(t, _), do: t

  # de Bruijn 0 is the nearest binder = last peeled λ = x#{depth-1}.
  defp emit_db({:var, i}, depth, _book), do: "x#{depth - 1 - i}"
  defp emit_db(:ze, _, _book), do: "0"
  defp emit_db(:one, _, _book), do: ":tt"
  defp emit_db({:su, u}, d, book), do: "{:suc, #{emit_db(u, d, book)}}"
  defp emit_db({:def, n}, _, _book), do: safe(n)
  defp emit_db({:ann, e, _}, d, book), do: emit_db(e, d, book)
  defp emit_db(:rfl, _, _book), do: ":refl"
  defp emit_db({:rwt, _, _, t}, d, book), do: emit_db(t, d, book)

  defp emit_db({:lam, :erased, _, t}, d, book), do: emit_db(t, d + 1, book)

  defp emit_db({:lam, _, _, t}, d, book) do
    "fn x#{d} -> #{emit_db(t, d + 1, book)} end"
  end

  defp emit_db({:left, t}, d, book), do: "{:left, #{emit_db(t, d, book)}}"
  defp emit_db({:right, t}, d, book), do: "{:right, #{emit_db(t, d, book)}}"

  defp emit_db({:msum, e, _p, l, r}, d, book) do
    """
    case #{emit_db(e, d, book)} do
      {:left, x#{d}} -> #{emit_db(l, d + 1, book)}
      {:right, x#{d}} -> #{emit_db(r, d + 1, book)}
    end
    """
    |> String.trim()
  end

  defp emit_db(:lnil, _, _book), do: "[]"
  defp emit_db({:cons, a, as}, d, book), do: "[#{emit_db(a, d, book)} | #{emit_db(as, d, book)}]"

  defp emit_db({:mlst, e, _p, n, c}, d, book) do
    """
    case #{emit_db(e, d, book)} do
      [] -> #{emit_db(n, d, book)}
      [x#{d} | x#{d + 1}] -> #{emit_db(c, d + 2, book)}
    end
    """
    |> String.trim()
  end

  defp emit_db({:mnat, e, _p, z, s}, d, book) do
    """
    case #{emit_db(e, d, book)} do
      0 -> #{emit_db(z, d, book)}
      {:suc, x#{d}} -> #{emit_db(s, d + 1, book)}
    end
    """
    |> String.trim()
  end

  defp emit_db({:memp, _, _}, _, _book), do: "raise \"Empty\""

  defp emit_db({:munit, e, _, u}, d, book) do
    "(#{emit_db(e, d, book)}; #{emit_db(u, d, book)})"
  end

  defp emit_db({:pair, a, b}, d, book), do: "{#{emit_db(a, d, book)}, #{emit_db(b, d, book)}}"
  defp emit_db({:fst, t}, d, book), do: "elem(#{emit_db(t, d, book)}, 0)"
  defp emit_db({:snd, t}, d, book), do: "elem(#{emit_db(t, d, book)}, 1)"

  defp emit_db({:unf, seed, f}, d, book) do
    "Stream.unfold(#{emit_db(seed, d, book)}, #{emit_db(f, d, book)})"
  end

  defp emit_db({:ucons, s}, d, book) do
    "(fn s -> {s |> Enum.take(1) |> hd(), Stream.drop(s, 1)} end).(#{emit_db(s, d, book)})"
  end

  defp emit_db({:app, _, _} = t, d, book) do
    {h, args} = spine(t, [])

    case h do
      {:def, n} ->
        live = live_args(book, n, args, d)
        "#{safe(n)}(#{Enum.join(live, ", ")})"

      _ ->
        Enum.reduce(args, emit_db(h, d, book), fn a, acc ->
          "#{acc}.(#{emit_db(a, d, book)})"
        end)
    end
  end

  defp emit_db(_, _, _book), do: "raise \"erased term\""

  defp live_args(book, name, args, d) do
    case Enum.find(book, &(&1.name == name)) do
      nil ->
        Enum.map(args, &emit_db(&1, d, book))

      dfn ->
        {:ok, ty} = Ast.to_db(dfn.type)
        qtys = qty_spine(ty)

        args
        |> Enum.zip(qtys ++ List.duplicate(:affine, length(args)))
        |> Enum.reject(fn {_, q} -> q == :erased end)
        |> Enum.map(fn {a, _} -> emit_db(a, d, book) end)
    end
  end

  defp qty_spine({:pi, q, _, b}), do: [q | qty_spine(b)]
  defp qty_spine(_), do: []

  defp spine({:app, f, a}, acc), do: spine(f, [a | acc])
  defp spine(h, acc), do: {h, acc}

  defp safe(name) do
    name
    |> String.replace("-", "_")
    |> String.replace("'", "_")
  end

  defp indent(s, n) do
    pad = String.duplicate(" ", n)

    s
    |> String.split("\n")
    |> Enum.map(&(pad <> &1))
    |> Enum.join("\n")
  end
end
