defmodule Muro.Emit do
  @moduledoc """
  Emit run definitions to Elixir. Specs and evidence erase.
  A spec never becomes evidence. Evidence never becomes a run.
  """

  alias Muro.Ast

  def emit_module(module, book) when is_atom(module) do
    runs = Enum.filter(book, &(&1.mode == :run))
    funs = runs |> Enum.map(&emit_def/1) |> Enum.join("\n\n")

    """
    defmodule #{inspect(module)} do
      # Generated by Muro. Evidence never becomes a run.

    #{indent(funs, 2)}
    end
    """
  end

  defp emit_def(%{name: name, type: ty, body: body} = d) do
    {:ok, ty_db} = Ast.to_db(ty)
    {:ok, body_db} = Ast.to_db(body)
    {erased, arity} = telescope(ty_db, 0, [])
    inner = peel_lams(body_db, arity)

    args =
      0..(arity - 1)//1
      |> Enum.reject(&(&1 in erased))
      |> Enum.map(&"x#{&1}")

    expr = emit_db(inner, arity)
    kw = if Map.get(d, :export, true), do: "def", else: "defp"

    if args == [] do
      "#{kw} #{safe(name)} do\n  #{expr}\nend"
    else
      "#{kw} #{safe(name)}(#{Enum.join(args, ", ")}) do\n  #{expr}\nend"
    end
  end

  defp telescope({:pi, :erased, _, b}, i, er), do: telescope(b, i + 1, [i | er])
  defp telescope({:pi, _, _, b}, i, er), do: telescope(b, i + 1, er)
  defp telescope(_, i, er), do: {er, i}

  defp peel_lams({:lam, _, _, t}, n) when n > 0, do: peel_lams(t, n - 1)
  defp peel_lams(t, _), do: t

  # de Bruijn 0 is the nearest binder = last peeled λ = x#{depth-1}.
  defp emit_db({:var, i}, depth), do: "x#{depth - 1 - i}"
  defp emit_db(:ze, _), do: "0"
  defp emit_db(:one, _), do: ":tt"
  defp emit_db({:su, u}, d), do: "{:suc, #{emit_db(u, d)}}"
  defp emit_db({:def, n}, _), do: safe(n)
  defp emit_db({:ann, e, _}, d), do: emit_db(e, d)
  defp emit_db(:rfl, _), do: ":refl"
  defp emit_db({:rwt, _, _, t}, d), do: emit_db(t, d)

  defp emit_db({:lam, :erased, _, t}, d), do: emit_db(t, d + 1)

  defp emit_db({:lam, _, _, t}, d) do
    "fn x#{d} -> #{emit_db(t, d + 1)} end"
  end

  defp emit_db({:mnat, e, _p, z, s}, d) do
    """
    case #{emit_db(e, d)} do
      0 -> #{emit_db(z, d)}
      {:suc, x#{d}} -> #{emit_db(s, d + 1)}
    end
    """
    |> String.trim()
  end

  defp emit_db({:memp, _, _}, _), do: "raise \"Empty\""

  defp emit_db({:munit, e, _, u}, d) do
    "(#{emit_db(e, d)}; #{emit_db(u, d)})"
  end

  defp emit_db({:app, _, _} = t, d) do
    {h, args} = spine(t, [])

    case h do
      {:def, n} ->
        "#{safe(n)}(#{Enum.map(args, &emit_db(&1, d)) |> Enum.join(", ")})"

      _ ->
        Enum.reduce(args, emit_db(h, d), fn a, acc ->
          "#{acc}.(#{emit_db(a, d)})"
        end)
    end
  end

  defp emit_db(_, _), do: "raise \"erased term\""

  defp spine({:app, f, a}, acc), do: spine(f, [a | acc])
  defp spine(h, acc), do: {h, acc}

  defp safe(name), do: String.replace(name, "-", "_")

  defp indent(s, n) do
    pad = String.duplicate(" ", n)

    s
    |> String.split("\n")
    |> Enum.map(&(pad <> &1))
    |> Enum.join("\n")
  end
end
